FROM ubuntu@sha256:626ffe58f6e7566e00254b638eb7e0f3b11d4da9675088f4781a50ae288f3322

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    socat \
    python3

RUN install -d -m 0700 /challenge

COPY picker-I.py /app/
COPY setup-challenge.py /app/
WORKDIR /app/


ARG FLAG_FORMAT
ARG FLAG
ARG SEED

RUN python3 /challenge/setup-challenge.py
RUN tar czvf /challenge/artifacts.tar.gz picker-I.py


COPY start.sh /opt/start.sh

EXPOSE 5555
# PUBLISH 5555 AS socat
CMD ["/opt/start.sh"]
