
FROM httpd:2.4


# Install challenge dependencies within the image
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    python3


COPY ./public-html/ /usr/local/apache2/htdocs/


# Create challenge dir for metadata.json and other file artifacts
RUN mkdir /challenge


# Bring in all environment vars from cmgr
ARG SEED
ARG FLAG_FORMAT
ARG FLAG


COPY config-box.py /challenge/config-box.py
RUN python3 /challenge/config-box.py


EXPOSE 80
# PUBLISH 80 AS web
