# This is a copy of Dockerfile that has a couple supporting lines and
# 1 error in it. Try to build it and see if you can spot the discrepancy.

FROM ubuntu:20.04


# Install challenge dependencies within the image
RUN apt-get update && apt-get install -y \
    openssh-server \
    socat \
    python3


# Create challenge dir for metadata.json and other file artifacts
RUN mkdir /challenge


# Bring in all environment vars from cmgr
#ARG SEED
#ARG FLAG_FORMAT
#ARG FLAG
# TODO : remove below and uncomment above
ENV FLAG="picoCTF{12345678}"
ENV SEED="9001"


COPY config-box.py /challenge/config-box.py
COPY profile /challenge/profile
COPY instructions-to-2of3.txt /challenge/instructions-to-2of3.txt
COPY instructions-to-3of3.txt /challenge/instructions-to-3of3.txt
COPY start.sh /opt/start.sh

RUN python3 config-box.py



EXPOSE 5555
# PUBLISH 5555 AS ssh
CMD ["/opt/start.sh"]
